using HttpTokenize.Substitutions;
using HttpTokenize.Tokenizers;
using HttpTokenize.Tokens;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace HttpTokenize.RequestSequence
{
    public class RequestSequence : IEnumerable<Stage>
    {
        private readonly List<Stage> Stages;

        // The full set of responses generated by this sequence.
        public List<Response>? Responses { get; internal set; }

        // Seed tokens for this request sequence.
        public TokenCollection InitialTokens { get; internal set; }

        // The full set of tokens generated by this sequence.
        // The results of each individual request can be accessed through Responses.
        // public TokenCollection? ResultingTokens { get; internal set; }

        public RequestSequence(TokenCollection initialTokens)
        {
            Stages = new List<Stage>();
            Responses = null;
            InitialTokens = initialTokens;
        }

        public async Task<List<Response>> Execute(HttpClient client, List<IResponseTokenizer> responseTokenizers)
        {
            Responses = new List<Response>();
            // ResultingTokens = new TokenCollection(InitialTokens);

            // For each request.
            for (int i = 0; i < Stages.Count; ++i)
            {
                // Make the request.
                try
                {
                    // Apply all substitutions.
                    Request request = Stages[i].Request.Clone();
                    foreach (ISubstitution substitution in Stages[i].Substitutions)
                    {
                        substitution.MakeSubstitution(Responses, request);
                    }

                    HttpResponseMessage rawResponse = await client.SendAsync(request.GenerateRequest());
                    Response response = new Response(rawResponse.StatusCode, await rawResponse.Content.ReadAsStringAsync());
                    if (rawResponse.Content.Headers.Contains("Content-Type"))
                    {
                        response.Headers.Add("Content-Type", rawResponse.Content.Headers.ContentType.ToString());
                    }

                    response.Tokenize(responseTokenizers);
                    Responses.Add(response);
                }
                catch (TimeoutException ex)
                {
                    Response response = new Response(System.Net.HttpStatusCode.RequestTimeout, "//Timeout.");
                    Responses.Add(response);
                }
                catch (TaskCanceledException ex)
                {
                    Response response = new Response(System.Net.HttpStatusCode.RequestTimeout, "//Timeout.");
                    Responses.Add(response);
                }
                catch (Exception ex)
                {
                    Response response = new Response(System.Net.HttpStatusCode.RequestTimeout, ex.Message);
                    Responses.Add(response);
                }
            }

            return Responses;
        }

        public void Add(Stage stage)
        {
            Stages.Add(stage);
            Responses = null;
        }

        public Stage Get(int index)
        {
            return Stages[index];
        }

        public int Count()
        {
            return Stages.Count;
        }

        public RequestSequence Copy()
        {
            TokenCollection initialTokens = new TokenCollection(InitialTokens);
            RequestSequence sequence = new RequestSequence(initialTokens);
            foreach (Stage stage in Stages)
            {
                sequence.Add(stage.Copy());
            }
            return sequence;
        }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("RequestSequence\n");
            foreach (Stage stage in Stages)
            {
                foreach (ISubstitution sub in stage.Substitutions)
                {
                    sb.Append("\t\t" + sub.ToString() + "\n");
                }
                sb.Append("\t" + stage.Request.Method.ToString() + " " + stage.Request.Url.ToString() + "\n");
            }
            return sb.ToString();
        }

        public IEnumerator<Stage> GetEnumerator()
        {
            return ((IEnumerable<Stage>)Stages).GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return ((IEnumerable<Stage>)Stages).GetEnumerator();
        }
    }
}
