// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebView.Data;

namespace WebView.Migrations
{
    [DbContext(typeof(KnownEndpointContext))]
    [Migration("20191010055039_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebView.Models.EndpointModel", b =>
                {
                    b.Property<int>("EndpointModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("EndpointModelID");

                    b.ToTable("KnownEndpoints");
                });

            modelBuilder.Entity("WebView.Models.RequestModel", b =>
                {
                    b.Property<int>("RequestModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EndpointModelID")
                        .HasColumnType("int");

                    b.Property<string>("Host")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestModelID");

                    b.HasIndex("EndpointModelID");

                    b.ToTable("KnownRequests");
                });

            modelBuilder.Entity("WebView.Models.RequestModel", b =>
                {
                    b.HasOne("WebView.Models.EndpointModel", "Endpoint")
                        .WithMany("Requests")
                        .HasForeignKey("EndpointModelID");
                });
#pragma warning restore 612, 618
        }
    }
}
